apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
  labels:
    app: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secrets
              key: password
        - name: SQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: sql-secrets
              key: username
